// src/component/header/Header.svelte
<script>
  import { Header } from "./header";

  let data;
  const setData = (newData) => {data = newData};
  const header = new Header(setData);
</script>

<style>@import url("./header.css");</style>


<!-- svelte-ignore component-name-lowercase -->
<header class="header flex-i-col" style={`zoom: ${data.zoom}`}>
  <div class="flex-i-col">
    <img src={data.imageMap.portraitV} alt="Sailor V" />
    <img src={data.imageMap.portraitJupiter} alt="Sailor Jupiter" />
    <img src={data.imageMap.portraitMercury} alt="Sailor Mercury" />
    <img
      class="pssmeLogo"
      src={data.imageMap.pssmeLogo}
      alt="Pretty Soldier Sailor Moon Editor (Arcade)"
    />
    <img src={data.imageMap.portraitMoon} alt="Sailor Moon" />
    <img src={data.imageMap.portraitMars} alt="Sailor Mars" />
    <img src={data.imageMap.portraitVenus} alt="Sailor Venus" />
  </div>
</header>

// src/components/header/HeaderComponent.jsx
import React from 'react';

import imageMap from '../../data/ImageMap';

import "./Header.css";


const HeaderComponent = (props) =>
{
	let logoTitle = "Pretty Soldier Sailor Moon Editor (Arcade)";
			
	return (
		<header
			className="header colLinedFlex"
			style={{zoom: props.zoom}}
		>
			<div className="colLinedFlex">
				<div className="colLinedFlex">
					<img src={imageMap.portraitV} title="Sailor V"/>
					<img
						src={imageMap.portraitJupiter}
						title="Sailor Jupiter"
					/>
					<img
						src={imageMap.portraitMercury}
						title="Sailor Mercury"
					/>
					<img
						className="pssmeLogo"
						src={imageMap.pssmeLogo}
						title={logoTitle}
					/>
					<img
						src={imageMap.portraitMoon}
						title="Sailor Moon"
					/>
					<img
						src={imageMap.portraitMars}
						title="Sailor Mars"
					/>
					<img
						src={imageMap.portraitVenus}
						title="Sailor Venus"
					/>
				</div>
			</div>
		</header>
	);
}


export default HeaderComponent;
